MONSTERS = {
    "robalo-riva-sombria": {
        "name": "Robalo de Riva Sombria",
        "challenge": "1/2",
        "xp": 100,
        "hp": 22,
        "armor": 13,
        "summary": "Predador anfibio que embosca presas em margens escuras e cavernas umidas.",
        "abilities": [
            "Mordida: 1d6 + 2 de dano perfurante.",
            "Fuga Subaquatica: move 15 pes em agua sem provocar reacao.",
            "Sombra do Pantano: some em sombras e trevas.",
        ],
        "drops": [
            {"name": "Escama do Robalo", "value": 5},
            {"name": "Dente de Robalo", "value": 7},
        ],
        "dc": 11,
        "favored_tactics": {"precision", "instinct"},
    },
    "goblin-cacador": {
        "name": "Goblin Cacador",
        "challenge": "1/4",
        "xp": 50,
        "hp": 7,
        "armor": 14,
        "summary": "Emboscador de trilhas estreitas, usa cobertura e ataca primeiro.",
        "abilities": [
            "Arco Curto: 1d6 + 2 de dano perfurante.",
            "Furtividade: se esconde em rochas e arvores.",
            "Estrategia de Emboscada: vantagem no primeiro ataque.",
        ],
        "drops": [
            {"name": "Arco de Curto Alcance", "value": 10},
            {"name": "Dado de Ouro", "value": 2},
            {"name": "Pele de Goblin", "value": 5},
        ],
        "dc": 10,
        "favored_tactics": {"precision", "mystic"},
    },
    "aranha-fogo": {
        "name": "Aranha de Fogo das Cavernas",
        "challenge": "1",
        "xp": 200,
        "hp": 18,
        "armor": 14,
        "summary": "Predadora ardente que ocupa tetos e corredores estreitos com teias em chamas.",
        "abilities": [
            "Mordida Ardente: 1d6 + 2 perfurante e 2d6 fogo.",
            "Teia Flamejante: prende alvos e incendeia a area.",
            "Escalada Agil: percorre paredes e tetos.",
        ],
        "drops": [
            {"name": "Seda Flamejante", "value": 12},
            {"name": "Veneno de Aranha", "value": 8},
        ],
        "dc": 13,
        "favored_tactics": {"mystic", "precision"},
    },
    "lupus": {
        "name": "Lupus da Floresta Profunda",
        "challenge": "1",
        "xp": 200,
        "hp": 24,
        "armor": 15,
        "summary": "Caçador ancestral de matas fechadas, marca a presa e persegue sem hesitar.",
        "abilities": [
            "Mordida de Cacador: 1d6 + 2 perfurante.",
            "Sentidos Agucados: rastreia por som e cheiro.",
            "Mestre da Cacada: ganha vantagem contra o alvo marcado.",
        ],
        "drops": [
            {"name": "Pelagem Densa", "value": 10},
            {"name": "Dente de Lupus", "value": 8},
            {"name": "Coracao de Lupus", "value": 20},
        ],
        "dc": 13,
        "favored_tactics": {"instinct", "power"},
    },
    "duende-bosque": {
        "name": "Duende do Bosque",
        "challenge": "1/4",
        "xp": 50,
        "hp": 9,
        "armor": 12,
        "summary": "Guardiao ferino da mata, ataca de sombras verdes e de galhos densos.",
        "abilities": [
            "Besta de Caca: 1d6 perfurante.",
            "Furtividade nas Sombras: some em vegetacao sombria.",
            "Punicao da Natureza: dano extra perto de arvores.",
        ],
        "drops": [
            {"name": "Folha Enfeiticada", "value": 8},
            {"name": "Besta de Caca", "value": 15},
        ],
        "dc": 10,
        "favored_tactics": {"mystic", "precision"},
    },
    "cobra-veneno": {
        "name": "Cobra de Veneno Veloz",
        "challenge": "1/4",
        "xp": 50,
        "hp": 15,
        "armor": 13,
        "summary": "Serpente rapida que envenena e recua antes da resposta do alvo.",
        "abilities": [
            "Mordida Venenosa: 1d4 + 2 perfurante e 1d6 veneno.",
            "Fuga Rapida: reposiciona-se com velocidade.",
            "Sentido de Perigo: percebe ameacas a curta distancia.",
        ],
        "drops": [
            {"name": "Veneno da Cobra", "value": 5},
            {"name": "Pele de Cobra", "value": 8},
        ],
        "dc": 10,
        "favored_tactics": {"precision", "instinct"},
    },
    "bufalo-selvagem": {
        "name": "Bufalo Selvagem",
        "challenge": "1/2",
        "xp": 100,
        "hp": 30,
        "armor": 15,
        "summary": "Massa bruta de musculo e couro, capaz de quebrar linhas com uma investida.",
        "abilities": [
            "Chifre Afiado: 2d6 + 3 contundente.",
            "Investida: derruba e prensa a vitima.",
            "Furia Animal: acelera em disparada curta.",
        ],
        "drops": [
            {"name": "Chifre Afiado", "value": 10},
            {"name": "Carne de Bufalo", "value": 8},
            {"name": "Pele Grossa", "value": 12},
        ],
        "dc": 12,
        "favored_tactics": {"power"},
    },
    "sapo-gigante": {
        "name": "Sapo Gigante",
        "challenge": "1/4",
        "xp": 50,
        "hp": 18,
        "armor": 12,
        "summary": "Anfibio grotesco que alterna saltos e jatos corrosivos em terreno lodoso.",
        "abilities": [
            "Salto Gigante: atravessa obstaculos e recua.",
            "Mordida Viscosa: 1d6 + 1 perfurante.",
            "Veneno Digestivo: cone curto de dano venenoso.",
        ],
        "drops": [
            {"name": "Pele Viscosa", "value": 5},
            {"name": "Veneno Digestivo", "value": 2},
        ],
        "dc": 10,
        "favored_tactics": {"instinct", "mystic"},
    },
    "lobisomem-jovem": {
        "name": "Lobisomem Jovem",
        "challenge": "1",
        "xp": 200,
        "hp": 27,
        "armor": 13,
        "summary": "Guardiao feroz tomado por energia lunar e dor ancestral nos arredores da caverna.",
        "abilities": [
            "Mordida de Lobisomem: 1d6 + 2 perfurante.",
            "Garras Afiadas: 1d4 + 2 cortante.",
            "Regeneracao Lunar: recupera vida sob o luar.",
        ],
        "drops": [
            {"name": "Dente de Lobisomem", "value": 8},
            {"name": "Pelo de Lobisomem", "value": 12},
            {"name": "Prata Enferrujada", "value": 10},
        ],
        "dc": 13,
        "favored_tactics": {"power", "instinct"},
    },
    "raposa-fogo": {
        "name": "Raposa de Fogo",
        "challenge": "1/4",
        "xp": 50,
        "hp": 13,
        "armor": 14,
        "summary": "Criatura agil e incendiaria, excelente para um confronto rapido de farm.",
        "abilities": [
            "Mordida Flamejante: 1d6 + 2 perfurante e 1d4 fogo.",
            "Corrida Incendiaria: deixa trilha de chamas.",
            "Furtividade: desaparece em sombra e vegetacao.",
        ],
        "drops": [
            {"name": "Pelo Flamejante", "value": 8},
            {"name": "Veneno Flamejante", "value": 12},
            {"name": "Caroco de Fruta Exotica", "value": 5},
        ],
        "dc": 10,
        "favored_tactics": {"precision", "mystic"},
    },
    "passaro-assassino": {
        "name": "Passaro Assassino do Bosque",
        "challenge": "1/2",
        "xp": 100,
        "hp": 18,
        "armor": 14,
        "summary": "Ave de mergulho violento que domina clareiras e trilhas aereas.",
        "abilities": [
            "Pico Afiado: 1d6 + 2 perfurante.",
            "Ataque Aereo: 2d6 perfurante em mergulho.",
            "Manobra Agil: desvia e sobe novamente.",
        ],
        "drops": [
            {"name": "Penas Afiadas", "value": 5},
            {"name": "Garras de Passaro", "value": 10},
            {"name": "Olho do Passaro", "value": 15},
        ],
        "dc": 11,
        "favored_tactics": {"precision", "instinct"},
    },
}

TACTICS = {
    "power": {
        "name": "Assalto Frontal",
        "summary": "Usa forca, presenca e resistencia para esmagar o inimigo.",
    },
    "precision": {
        "name": "Precisao e Movimento",
        "summary": "Busca o angulo certo, o flanco e a abertura mais curta.",
    },
    "mystic": {
        "name": "Leitura Arcana",
        "summary": "Canaliza magia, astucia ou disciplina espiritual para vencer.",
    },
    "instinct": {
        "name": "Instinto de Sobrevivencia",
        "summary": "Luta por percepcao, adaptacao e leitura do terreno.",
    },
}

CHAPTER_SCENES = {
    "chapter_entry": {
        "type": "narrative",
        "act": 1,
        "eyebrow": "Ato 1",
        "title": "Ruas Baixas de Elandoria",
        "lead": "Voce desperta nas ruas baixas de Elandoria, entre tavernas, guardas cansados e rumores sobre algo inquieto nos arredores do reino.",
        "body": [
            "A cidade vive no presente, mas nunca escapou totalmente da memoria de sua fundacao. Em tavernas e esquinas, nomes antigos ainda voltam em voz baixa.",
            "Alguns falam de trilhas fechadas, de um memorial antigo e de gente que saiu para investigar e nao voltou. Nada e claro ainda, e voce precisa encontrar seu primeiro rumo.",
        ],
        "options": [
            {"action": "go_goblin", "label": "Seguir pela Trilha do Memorial", "summary": "Voce deixa a cidade e segue o rumor mais perigoso."},
            {"action": "go_robalo", "label": "Descer para a Riva Sombria", "summary": "Voce investiga um caminho umido e pouco vigiado nos limites do reino."},
        ],
    },
    "encounter_goblin": {
        "type": "encounter",
        "act": 1,
        "eyebrow": "Ato 1",
        "title": "Emboscada na Trilha do Memorial",
        "lead": "Um goblin caçador ocupa a passagem com arco curto e vantagem de terreno.",
        "body": [
            "A trilha afunila entre pedras antigas e marcas esquecidas de guerra. O disparo vem antes do aviso.",
        ],
    },
    "encounter_robalo": {
        "type": "encounter",
        "act": 1,
        "eyebrow": "Ato 1",
        "title": "Aguas da Riva Sombria",
        "lead": "Nas margens encharcadas, algo pesado rompe a agua negra e mira sua perna.",
        "body": [
            "O terreno trai cada passo. O primeiro erro vira alimento para um predador de riva.",
        ],
    },
    "act_two_crossroads": {
        "type": "narrative",
        "act": 2,
        "eyebrow": "Ato 2",
        "title": "Pistas na borda da mata",
        "lead": "Os primeiros sinais confirmam que algo protege o caminho para a caverna de Freya.",
        "body": [
            "Marcas antigas, galhos partidos e trilhas recentes sugerem que a area virou um corredor de criaturas agressivas e pequenos predadores oportunistas.",
            "Voce encontra tambem um simbolo antigo de Elandoria gravado em pedra, quase tomado por musgo. A caverna sagrada parece mais proxima.",
        ],
        "options": [
            {"action": "go_duende", "label": "Entrar na clareira do bosque", "summary": "Area viva, silenciosa e protegida por olhos ocultos."},
            {"action": "go_cobra", "label": "Seguir pela trilha baixa", "summary": "Terreno rapido, seco e repleto de risco venenoso."},
            {"action": "go_raposa", "label": "Farmar nas redondezas", "summary": "Uma caçada curta antes de avancar."},
        ],
    },
    "encounter_duende": {
        "type": "encounter",
        "act": 2,
        "eyebrow": "Ato 2",
        "title": "Guardiao do Bosque",
        "lead": "Um duende do bosque toma sua presenca como invasao e usa a propria mata como arma.",
        "body": [
            "As folhas parecem cochichar antes do disparo. O inimigo nunca fica onde seus olhos esperam.",
        ],
    },
    "encounter_cobra": {
        "type": "encounter",
        "act": 2,
        "eyebrow": "Ato 2",
        "title": "Silvo na Trilha Baixa",
        "lead": "A cobra surge baixa, rapida e venenosa, ja pronta para o bote e a retirada.",
        "body": [
            "A trilha seca e estreita parece segura demais. Quando o solo vibra, o veneno ja esta em movimento.",
        ],
    },
    "encounter_raposa": {
        "type": "encounter",
        "act": 2,
        "eyebrow": "Ato 2",
        "title": "Caçada Curta",
        "lead": "Uma raposa de fogo cruza a vegetacao com chamas vivas presas ao pelo.",
        "body": [
            "O confronto e rapido, ideal para farmar recursos antes da rota principal.",
        ],
    },
    "act_three_threshold": {
        "type": "narrative",
        "act": 3,
        "eyebrow": "Ato 3",
        "title": "O limiar da caverna",
        "lead": "A entrada sagrada esta perto, mas os arredores sao guardados por bestas mais antigas e inteligentes.",
        "body": [
            "Entre pedras rachadas e raizes profundas, uma flor de prata com miolo dourado cresce sozinha, como se tivesse resistido ao tempo inteiro. Voce a recolhe com cuidado.",
            "A energia do lugar muda. O ar pesa. Seja pela mata mais fechada, seja pela boca escura da caverna, ha algo observando cada passo.",
        ],
        "options": [
            {"action": "go_aranha", "label": "Entrar pelos tuneis quentes", "summary": "Cheiro de fogo, teias e pedra rachada."},
            {"action": "go_lupus", "label": "Contornar pela mata profunda", "summary": "Sombras, olfato predatorio e passos circulares."},
            {"action": "go_passaro", "label": "Farmar na encosta", "summary": "Uma caçada extra para reforcar recursos."},
        ],
    },
    "encounter_aranha": {
        "type": "encounter",
        "act": 3,
        "eyebrow": "Ato 3",
        "title": "Teias sobre Pedra Quente",
        "lead": "O teto pulsa com fios vermelhos e o ar cheira a cinza antes mesmo da primeira mordida.",
        "body": [
            "A entrada mais curta para a caverna exige atravessar o dominio da aranha de fogo.",
        ],
    },
    "encounter_lupus": {
        "type": "encounter",
        "act": 3,
        "eyebrow": "Ato 3",
        "title": "Olhos na Mata Profunda",
        "lead": "O lupus nao ruge. Ele circula, avalia e espera o momento exato para marcar sua presa.",
        "body": [
            "A floresta se fecha ao redor da trilha. Cada galho quebrado parece parte da armadilha.",
        ],
    },
    "encounter_passaro": {
        "type": "encounter",
        "act": 3,
        "eyebrow": "Ato 3",
        "title": "Mergulho Assassino",
        "lead": "Na encosta, uma ave predadora rasga o silencio e cai em mergulho sobre voce.",
        "body": [
            "E um bom ponto de farm, mas o erro aqui vem do alto e termina depressa.",
        ],
    },
    "freya_legacy": {
        "type": "puzzle",
        "act": 4,
        "eyebrow": "Ato 4",
        "title": "O Legado de Freya",
        "lead": "No interior da caverna sagrada, a memoria de Freya foi transformada em prova para quem deseja seguir adiante.",
        "body": [
            "Tres espelhos mostram a gravidez revelada, o funeral sob chuva e a queda de Nyx Vandir. O caminho exige compreender o coracao de Rowan, nao apenas repetir nomes.",
            "Mais adiante, uma estatua segura um livro fechado sobre o futuro do reino. No altar final, a flor certa deve ocupar o espaco da esperanca.",
        ],
    },
    "encounter_lobisomem": {
        "type": "encounter",
        "act": 5,
        "eyebrow": "Ato 5",
        "title": "Guardiao Lunar da Memoria",
        "lead": "A resposta ao enigma rompe o selo e desperta um lobisomem jovem tomado por energia ancestral.",
        "body": [
            "A ultima prova nao e sobre lembrar Rowan e Freya. E sobre provar que voce pode suportar o peso desse legado.",
        ],
    },
    "chapter_complete": {
        "type": "complete",
        "act": 5,
        "eyebrow": "Ato 5",
        "title": "A memoria responde",
        "lead": "A prova foi vencida. O legado de Freya e Rowan agora toca diretamente o seu personagem.",
        "body": [
            "A caverna nao entregou apenas tesouro. Ela confirmou que o futuro de Elandoria pertence a quem compreende dor, paz e responsabilidade.",
            "Seu personagem deixa o local com novos recursos, um artefato estranho e a certeza de que a historia maior do reino apenas comecou.",
        ],
    },
}
